apiVersion: v1
kind: Service
metadata:
  labels:
    run: provider
  name: provider
  namespace: default

spec:
  clusterIP: 10.47.254.176
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32518
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: provider
  sessionAffinity: None
  type: LoadBalancer

